// Generated by CoffeeScript 1.7.1
var Point, a, b;

Point = (function() {
  Point.prototype.x = null;

  Point.prototype.y = null;

  function Point(x, y) {
    this.x = x;
    this.y = y;
  }

  Point.prototype.add = function(other) {
    return new Point(this.x + other.x, this.y + other.y);
  };

  Point.prototype.sub = function(other) {
    return new Point(this.x - other.x, this.y - other.y);
  };

  Point.prototype.dot = function(other) {
    return new Point(this.x * other.x, this.y * other.y);
  };

  Point.prototype.mult = function(other) {
    return new Point(this.x * other, this.y * other);
  };

  return Point;

})();

a = new Point(2, 4);

b = new Point(-5, 1);

console.log(a);

console.log(b);

console.log(a.add(b));

console.log(a.sub(b));

console.log(a.dot(b));

console.log(a.mult(5));
